version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production-minor-and-patch:
        dependency-type: "production"
        update-types: ["minor", "patch"]
      development-minor-and-patch:
        dependency-type: "development"
        update-types: ["minor", "patch"]
